name: "Check Deprecated Dependencies"
description: "Checking for deprecated JavaScript dependencies"
branding:
  icon: "package"
  color: "orange"
inputs:
  ignore: # packages to ignore
    description: "packages names to ignore"
    required: false
    default: "[]"
  root:
    description: "rootDir to search package.json files"
    required: false
    default: "."
outputs:
  deprecated: # output will be available to future steps
    description: "names of deprecated packages"
runs:
  using: "node12"
  main: "dist/index.js"
